### ISSUE TITLE
Setting SMTP env vars with docker-compose not being picked up by errbit app

### ISSUE THREAD

**Issue by jbwl** [errbit/errbit#1557]
### Step 2: Describe your environment

  * Errbit version: 0.10.0-dev
  * OS: Docker 27.3.1 on top of Ubuntu 24.04 

### Step 3: Describe the problem:

Errbit is not sending notifications via Email. I am trying to configure errbit to send via my SMTP server (Mandrill), and therefore I am setting the needed env vars in the docker-compose.yaml file (see below). 

#### Steps to reproduce:

  1. pull latest errbit from GitHub
  2. add the smtp env vars to docker-compose.yaml (anonymized here).

```
services:
  errbit:
    image: errbit/errbit:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - RACK_ENV=production
      - MONGO_URL=mongodb://mongo:27017/errbit
      - SECRET_KEY_BASE=supersecretkey
      - ERRBIT_EMAIL_FROM=my@email.address
      - EMAIL_DELIVERY_METHOD=smtp
      - SMTP_SERVER=smtp.mandrillapp.com
      - SMTP_PORT=587
      - SMTP_AUTHENTICATION=login
      - SMTP_USERNAME=user@domain.com
      - SMTP_PASSWORD=password
      - SMTP_DOMAIN=domain.com
      - SMTP_ENABLE_STARTTLS_AUTO=true
  mongo:
    image: mongo:4.1
    ports:
      - "27017"
```

  3. Restart the stack with `docker compose restart`

#### Observed Results:

Nothing is sent when an error is logged from my apps, but instead an error is produced for the errbit app saying: `Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25`.

#### Expected Results:

I am expecting Errbit to send via SMTP as per my config in docker-compose.yaml
