### ISSUE TITLE
Run docker container as read-only

### ISSUE THREAD

**Issue by biow0lf** [errbit/errbit#1847]
**WHY?**

Reduce attack surface on Errbit instances.

**How to test?**

```yaml
services:
  errbit:
    image: "errbit/errbit:latest"
    ports:
      - "3000:3000"
    read_only: true
    environment:
      RAILS_ENV: "production"
      MONGO_URL: "mongodb://mongo:27017/errbit"
```
